# Use the official Node.js image as a parent image
FROM node:current-alpine as builder

WORKDIR /app
COPY . .

RUN npm install
RUN npm run build

# Stage 2: Serve the React app using Nginx
FROM nginx:alpine
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /app/dist /usr/share/nginx/html
