// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: add_interest.sql

package db

import (
	"context"
)

const addInterest = `-- name: AddInterest :one
INSERT INTO interests (user_id, interest)
VALUES ($1, $2)
RETURNING id
`

type AddInterestParams struct {
	UserID   int32  `json:"user_id"`
	Interest string `json:"interest"`
}

func (q *Queries) AddInterest(ctx context.Context, arg AddInterestParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, addInterest, arg.UserID, arg.Interest)
	var id int32
	err := row.Scan(&id)
	return id, err
}
