// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: add_skill.sql

package db

import (
	"context"
	"database/sql"
)

const addSkill = `-- name: AddSkill :one
INSERT INTO skills (user_id, skill_description)
VALUES ($1, $2)
RETURNING id
`

type AddSkillParams struct {
	UserID           sql.NullInt32 `json:"user_id"`
	SkillDescription string        `json:"skill_description"`
}

func (q *Queries) AddSkill(ctx context.Context, arg AddSkillParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, addSkill, arg.UserID, arg.SkillDescription)
	var id int32
	err := row.Scan(&id)
	return id, err
}
