// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: delete_interest.sql

package db

import (
	"context"
)

const deleteInterest = `-- name: DeleteInterest :exec
DELETE FROM interests
WHERE id = $1
`

func (q *Queries) DeleteInterest(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteInterest, id)
	return err
}
