// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: delete_user.sql

package db

import (
	"context"
)

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE discord_id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, discordID string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, discordID)
	return err
}
