// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: delete_skill.sql

package db

import (
	"context"
)

const deleteSkill = `-- name: DeleteSkill :exec
DElETE FROM skills
WHERE id = $1
`

func (q *Queries) DeleteSkill(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteSkill, id)
	return err
}
