// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: get_user_id_by_discord_id.sql

package db

import (
	"context"
)

const getUserIDByDiscordID = `-- name: GetUserIDByDiscordID :one
SELECT id
FROM users
WHERE discord_id = $1
`

func (q *Queries) GetUserIDByDiscordID(ctx context.Context, discordID string) (int32, error) {
	row := q.db.QueryRowContext(ctx, getUserIDByDiscordID, discordID)
	var id int32
	err := row.Scan(&id)
	return id, err
}
