// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: get_user_from_session.sql

package db

import (
	"context"
)

const getUserIDFromSessionToken = `-- name: GetUserIDFromSessionToken :one
SELECT discord_id
FROM user_sessions
WHERE session_token = $1
`

func (q *Queries) GetUserIDFromSessionToken(ctx context.Context, sessionToken string) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserIDFromSessionToken, sessionToken)
	var discord_id string
	err := row.Scan(&discord_id)
	return discord_id, err
}
