// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: get_all_interests.sql

package db

import (
	"context"
)

const getAllInterests = `-- name: GetAllInterests :many
SELECT id, user_id, interest, created_at
FROM interests
`

func (q *Queries) GetAllInterests(ctx context.Context) ([]Interest, error) {
	rows, err := q.db.QueryContext(ctx, getAllInterests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Interest
	for rows.Next() {
		var i Interest
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Interest,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
