// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: get_user.sql

package db

import (
	"context"
	"database/sql"
)

const getUser = `-- name: GetUser :one
SELECT username, avatar_url 
FROM users
WHERE discord_id = $1
`

type GetUserRow struct {
	Username  string         `json:"username"`
	AvatarUrl sql.NullString `json:"avatar_url"`
}

func (q *Queries) GetUser(ctx context.Context, discordID string) (GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser, discordID)
	var i GetUserRow
	err := row.Scan(&i.Username, &i.AvatarUrl)
	return i, err
}
