// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
)

type Skill struct {
	ID               int32        `json:"id"`
	UserID           string       `json:"user_id"`
	SkillDescription string       `json:"skill_description"`
	CreatedAt        sql.NullTime `json:"created_at"`
}
