// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: update_user.sql

package db

import (
	"context"
	"database/sql"
)

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET username = $2, email = $3, avatar_url = $4, session_token = $5, updated_at = NOW()
WHERE discord_id = $1
`

type UpdateUserParams struct {
	DiscordID    string         `json:"discord_id"`
	Username     string         `json:"username"`
	Email        string         `json:"email"`
	AvatarUrl    sql.NullString `json:"avatar_url"`
	SessionToken sql.NullString `json:"session_token"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.DiscordID,
		arg.Username,
		arg.Email,
		arg.AvatarUrl,
		arg.SessionToken,
	)
	return err
}
