// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: update_interest.sql

package db

import (
	"context"
)

const updateInterest = `-- name: UpdateInterest :exec
UPDATE interests
SET interest = $2
WHERE id = $1
`

type UpdateInterestParams struct {
	ID       int32  `json:"id"`
	Interest string `json:"interest"`
}

func (q *Queries) UpdateInterest(ctx context.Context, arg UpdateInterestParams) error {
	_, err := q.db.ExecContext(ctx, updateInterest, arg.ID, arg.Interest)
	return err
}
