// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: update_skill.sql

package db

import (
	"context"
)

const updateSkill = `-- name: UpdateSkill :exec
UPDATE skills
SET skill_description = $2
WHERE id = $1
`

type UpdateSkillParams struct {
	ID               int32  `json:"id"`
	SkillDescription string `json:"skill_description"`
}

func (q *Queries) UpdateSkill(ctx context.Context, arg UpdateSkillParams) error {
	_, err := q.db.ExecContext(ctx, updateSkill, arg.ID, arg.SkillDescription)
	return err
}
